struct Money {
    cents int
    currency string [optional]
}

struct FulfillmentJob {
    id int
    status string
    name string
    printer_id int
    cost Money
}

interface FulfillmentJobsSystem {
    create(printer_id int, name string, cost Money) FulfillmentJob
    show_exception() int
    set_cost(cost Money) bool
}
